-- https://stackoverflow.com/questions/42304958/promise-not-resolved-after-a-validation-failure
func http_post_login(user: String): String begin
  concat(user, "-dummy")
end

func login(deferred: Promise(String), setDeferred: Promise*(String), user: String): Promise(String) begin
  let result = http_post_login(user) in
  setDeferred <- result;
  deferred
end

func LoginService(): Unit begin
  promise deferred, setDeferred: String in
  async while true begin
  -- Can't really imitate events or closures, but this shows what would happen if events were able to repeat
    if false then
      login(deferred, "user")
    else () end
  end
end
